
pipelines:
  default: &default_tests
    - parallel:
        - step:
            name: Build & Test 2.7.6
            image: gbrowdy/python-2.7.6
            script: &build_test
              - python setup.py sdist
              - pip install -f dist cart
              - python -m unittest discover
        - step:
            name: Build & Test 2.7
            image: python:2.7
            script: *build_test
        - step:
            name: Build & Test 3.3
            image: python:3.3
            script: *build_test
        - step:
            name: Build & Test 3.4
            image: python:3.4
            script: *build_test
        - step:
            name: Build & Test 3.5
            image: python:3.5
            script: *build_test
        - step:
            name: Build & Test 3.6
            image: python:3.6
            script: *build_test
        - step:
            name: Build & Test 3.7-rc
            image: python:3.7-rc
            script: *build_test
  tags:
    v*:
      - step: *default_tests
      - parallel:
        - step:
            name: Deploy to Test PyPI
            image: python:3.6
            trigger: manual
            deployment: test
            script: &build_upload
              - python setup.py sdist
              - ls dist
              - pip install twine
              - twine dist/*
            artifacts:
              - dist/*
        - step:
            name: Deploy to PyPI
            image: python:3.6
            trigger: manual
            deployment: production
            script: *build_upload
            artifacts:
              - dist/*
